export function getMetadataSystemPrompt(): string {
	return `You are an expert technical editor and content strategist.
Your task is to analyze a blog post and generate enriched metadata.
Focus on SEO, clear descriptions, and accurate categorization.
Return a JSON object.`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getMetadataUserPrompt(
	currentMetadata: unknown,
	contentSnippet: string,
): string {
	return `
Current Metadata: ${JSON.stringify(currentMetadata, null, 2)}

Blog Content (first 15000 chars):
${contentSnippet}

Analyze the content and provide the JSON output matching the schema:
- If description is empty, write a new one.
- Suggest 3-5 tags.
- Categorize into 'Tech', 'Humanities', 'Life', 'Reverie', or 'Unknown'.
- Populate 'seo' object with 'title', 'description', and 'keywords'.
- Populate 'seo.og' object with 'title', 'description' (optimized for social media sharing).
- Populate 'ai' object with:
    - illustration_prompt: Detailed prompt for an article illustration. Style: flat vector art, minimal, vibrant colors.
    - thumbnail_prompt: A simplified version of the illustration prompt suitable for small sizes.
`;
}

export function getImageSystemPrompt(): string {
	return `You are an expert art director.
Your task is to generate a creative image prompt for a blog post illustration.
Return a JSON object with 'illustration_prompt'.`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function getImageUserPrompt(
	currentMetadata: unknown,
	contentSnippet: string,
): string {
	return `
Current Metadata: ${JSON.stringify(currentMetadata, null, 2)}

Blog Content (snippet):
${contentSnippet}

Generate a single image prompt:
1. illustration_prompt: Detailed prompt for an article illustration. Style: flat vector art, minimal, vibrant colors.
   (The thumbnail will be automatically generated by resizing this image, so ensure the subject/composition works well at smaller sizes too).

Return JSON.
`;
}
